# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
#  server:
#    build:
#      context: .
#    ports:
#      - 8081:8081

  # LocalStack - Simula serviços AWS (S3, SQS, DynamoDB)
  localstack:
    user: root
    container_name: "localstack_main"
    image: localstack/localstack
    command: ["/bin/sh", "-c", "chmod +x /etc/localstack/init/ready.d/init-aws.sh && exec localstack start"]
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - SERVICES=s3,sqs,dynamodb         # Adicionado DynamoDB
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-west-2
    volumes:
      - "${PWD}/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh:ro"
      - "${PWD}/docker:/docker:ro"        # Monta diretório com schemas
      - "${maal:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD-SHELL", 'awslocal dynamodb list-tables --region us-west-2 || exit 1']
      interval: 15s
      timeout: 10s
      retries: 10

  # DynamoDB Admin - Interface web para gerenciar DynamoDB
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://localstack:4566"  # Aponta para LocalStack
      AWS_REGION: "us-west-2"
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
    depends_on:
      localstack:
        condition: service_healthy