# name: PR Workflow

# on:
#   pull_request:
#     branches:
#       - master
#     types:
#       - opened
#       - synchronize
#       - reopened
#   workflow_dispatch:  # Permite execução manual do workflow

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     environment: production
#     services:
#       mongodb:
#         image: mongodb/mongodb-community-server:7.0.16-ubuntu2204
#         env:
#           MONGO_INITDB_ROOT_USERNAME: myuser
#           MONGO_INITDB_ROOT_PASSWORD: mypassword
#         ports:
#           - 27017:27017
  
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Set up JDK 23
#         uses: actions/setup-java@v3
#         with:
#           distribution: 'temurin'
#           java-version: '23'

#       - name: Cache Gradle packages
#         uses: actions/cache@v4
#         with:
#           path: ~/.gradle/caches
#           key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#           restore-keys: |
#             ${{ runner.os }}-gradle-

#       - name: Grant execute permission for gradlew
#         run: chmod +x gradlew

#       - name: Clean Build Cache
#         run: ./gradlew clean build --refresh-dependencies

#       - name: Build with Gradle
#         run: ./gradlew build
#         env:
#           MONGO_INITDB_ROOT_USERNAME: myuser
#           MONGO_INITDB_ROOT_PASSWORD: mypassword
#           SPRING_URL_SERVICE_TECH: ${{ secrets.URL_SERVICE_TECH }} # Mapeia para a propriedade Spring
#           SPRING_DATA_MONGODB_URI: mongodb://myuser:mypassword@localhost:27017/admin
