name: Gerenciamento de Tags, Releases e Deploy

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Permite execução manual do workflow

permissions:
  contents: write  # Permite criar tags e releases

jobs:
  create-release:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Criar e enviar tag de versão
        id: create-tag
        run: |
          DATE_VERSION=$(date +'%Y%m%d')
          TAG_COUNT=$(git tag -l "v${DATE_VERSION}.*" | wc -l)
          TAG_COUNT=$((TAG_COUNT + 1))
          NEW_TAG="v${DATE_VERSION}.${TAG_COUNT}"
          git tag -a ${NEW_TAG} -m "Release ${NEW_TAG}"
          git push origin ${NEW_TAG}
          echo "tag=${NEW_TAG}" >> $GITHUB_OUTPUT

      - name: Criar Release no GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.create-tag.outputs.tag }}
          name: "Release ${{ steps.create-tag.outputs.tag }}"
          body: |
            ## Release Notes

            Esta release foi gerada automaticamente após alterações na branch main.

            ### Últimos Commits:
            ${{ github.event.head_commit.message }}

            ### Autor:
            ${{ github.event.head_commit.author.name }}

            ### Data:
            ${{ github.event.head_commit.timestamp }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
